name: Build E404 Kernel

on:
  workflow_dispatch:
    inputs:
      branch:
        type: choice
        description: Select branch
        options:
          - rebase-bpf
          - staging
          - staging-bpf

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          submodules: recursive
          fetch-depth: 1

      - name: Setup KernelSU
        run: |
          if [ -d KernelSU ] && [ ! -e drivers/kernelsu ]; then
            mkdir -p drivers
            ln -sf "$GITHUB_WORKSPACE/KernelSU" drivers/kernelsu
          fi

          ls -la drivers/kernelsu || true
      
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            bc \
            bison \
            build-essential \
            ccache \
            curl \
            flex \
            git \
            libssl-dev \
            lld \
            python3 \
            zstd

      - name: Download Neutron Clang
        run: |
          mkdir clang
          cd clang

          wget -O neutron.tar.zst \
          https://github.com/Neutron-Toolchains/clang-build-catalogue/releases/download/30072026/neutron-clang-30072026.tar.zst

          tar --zstd -xf neutron.tar.zst

          find . -name clang

      - name: Setup Toolchain
        run: |
          CLANG_BIN=$(find $GITHUB_WORKSPACE/clang -type f -name clang | head -1)
          echo "CLANG_BIN=$CLANG_BIN"

          echo "$(dirname $CLANG_BIN)" >> $GITHUB_PATH

          which clang
          clang --version

      - name: Build Kernel
        run: |
          export ARCH=arm64
          export SUBARCH=arm64

          make O=out vendor/munch_defconfig

          make -j$(nproc) O=out \
            CC=clang \
            LLVM=1 \
            LLVM_IAS=1

      - name: Clone AnyKernel3
        run: |
          git clone --depth=1 \
          https://github.com/kvsnr113/AnyKernel3.git AnyKernel3

      - name: Package Zip
        run: |
          cp out/arch/arm64/boot/Image AnyKernel3/
          cp out/arch/arm64/boot/dtb AnyKernel3/
          cp out/arch/arm64/boot/dtbo.img AnyKernel3/

          cd AnyKernel3
          zip -r9 ../E404-Kernel.zip *

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: E404-Kernel
          path: E404-Kernel.zip