name: Build E404 Kernel

on:
  workflow_dispatch:
    inputs:
      kernel_branch:
        description: "Branch to build"
        required: true
        default: "rebase-bpf"

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Clone Kernel Source
        run: |
          git clone \
            --recursive \
            --depth=1 \
            -b "${{ github.event.inputs.kernel_branch }}" \
            https://github.com/dumpcode404/xiaomi_sm8250_kernel_e404_fork.git kernel

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            bc \
            bison \
            build-essential \
            ccache \
            curl \
            flex \
            git \
            libssl-dev \
            lld \
            python3 \
            zstd

      - name: Download Neutron Clang
        run: |
          wget -O clang.tar.zst \
          https://github.com/Neutron-Toolchains/clang-build-catalogue/releases/download/30072026/neutron-clang-30072026.tar.zst

          mkdir -p clang
          tar --zstd -xf clang.tar.zst -C clang

          echo "=== TOOLCHAIN STRUCTURE ==="
          find clang | head -50

      - name: Setup Toolchain
        run: |
          CLANG_DIR=$(find $GITHUB_WORKSPACE/clang -type d -name bin | head -1)

          echo "CLANG_DIR=$CLANG_DIR"

          export PATH=$CLANG_DIR:$PATH

          which clang
          clang --version

          echo "PATH=$PATH" >> $GITHUB_ENV

      - name: Build Kernel
        working-directory: kernel
        run: |
          export ARCH=arm64
          export SUBARCH=arm64

          which clang
          clang --version

          make O=out vendor/munch_defconfig

          make -j$(nproc) \
            O=out \
            CC=clang \
            LLVM=1 \
            LLVM_IAS=1

      - name: Clone AnyKernel3
        run: |
          git clone --depth=1 \
          https://github.com/kvsnr113/AnyKernel3.git AnyKernel3

      - name: Package Kernel
        run: |
          cp kernel/out/arch/arm64/boot/Image AnyKernel3/
          cp kernel/out/arch/arm64/boot/dtb AnyKernel3/
          cp kernel/out/arch/arm64/boot/dtbo.img AnyKernel3/

          cd AnyKernel3
          zip -r9 ../E404-Kernel.zip *

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: E404-Kernel
          path: E404-Kernel.zip